CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Core cluster table
CREATE TABLE IF NOT EXISTS klaster (
  klaster_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama_klaster text NOT NULL,
  klaster_role text
);

-- Auth / user table used throughout the codebase
CREATE TABLE IF NOT EXISTS "User" (
  user_id uuid PRIMARY KEY,
  nama text NOT NULL,
  email text NOT NULL UNIQUE,
  nomor_telepon text UNIQUE,
  password text NOT NULL,
  role text NOT NULL DEFAULT 'user',
  klaster_id integer REFERENCES klaster (klaster_id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Categories / accounts mapping for neraca and product grouping
CREATE TABLE IF NOT EXISTS kategorial (
  kategori_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama text NOT NULL,
  jenis text NOT NULL,
  klaster_id integer REFERENCES klaster (klaster_id) ON DELETE SET NULL,
  user_id uuid REFERENCES "User" (user_id) ON DELETE SET NULL,
  neraca_identifier integer,
  sub_kelompok text
);

-- Products belong to a category and may be owned by a user or cluster
CREATE TABLE IF NOT EXISTS produk (
  produk_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama text NOT NULL,
  kategori_id integer REFERENCES kategorial (kategori_id) ON DELETE SET NULL,
  created_by uuid REFERENCES "User" (user_id) ON DELETE SET NULL,
  klaster_id integer REFERENCES klaster (klaster_id) ON DELETE SET NULL
);

-- Cash/account master data
CREATE TABLE IF NOT EXISTS akun_kas (
  akun_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama text NOT NULL,
  deskripsi text,
  user_id uuid REFERENCES "User" (user_id) ON DELETE SET NULL,
  klaster_id integer REFERENCES klaster (klaster_id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  saldo_awal integer NOT NULL DEFAULT 0,
  saldo_akhir integer NOT NULL DEFAULT 0
);

-- Financial report header
CREATE TABLE IF NOT EXISTS lapkeuangan (
  id_laporan uuid PRIMARY KEY,
  id_user uuid REFERENCES "User" (user_id) ON DELETE SET NULL,
  akun_id integer REFERENCES akun_kas (akun_id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  jenis text NOT NULL,
  deskripsi text,
  debit integer NOT NULL DEFAULT 0,
  kredit integer NOT NULL DEFAULT 0,
  tanggal date,
  klaster_id integer REFERENCES klaster (klaster_id) ON DELETE SET NULL
);

-- Financial report detail lines
CREATE TABLE IF NOT EXISTS detaillaporanbarang (
  id_detail integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  laporan_id uuid NOT NULL REFERENCES lapkeuangan (id_laporan) ON DELETE CASCADE,
  produk_id integer REFERENCES produk (produk_id) ON DELETE SET NULL,
  jumlah integer NOT NULL,
  subtotal integer NOT NULL
);

-- Cluster invitations
CREATE TABLE IF NOT EXISTS klaster_invite (
  invite_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  klaster_id integer NOT NULL REFERENCES klaster (klaster_id) ON DELETE CASCADE,
  target_email text,
  target_phone text,
  target_user_id uuid REFERENCES "User" (user_id) ON DELETE SET NULL,
  role text NOT NULL DEFAULT 'member',
  status text NOT NULL DEFAULT 'pending',
  token text NOT NULL UNIQUE,
  max_uses integer NOT NULL DEFAULT 1,
  used_count integer NOT NULL DEFAULT 0,
  expires_at timestamptz,
  created_by uuid REFERENCES "User" (user_id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  responded_at timestamptz
);

-- Rules used to auto-map category patterns to sub groups
CREATE TABLE IF NOT EXISTS kategori_auto_rules (
  rule_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pattern text NOT NULL,
  target_sub_kelompok text NOT NULL,
  priority integer NOT NULL DEFAULT 1000,
  user_id uuid REFERENCES "User" (user_id) ON DELETE SET NULL,
  klaster_id integer REFERENCES klaster (klaster_id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Helpful indexes for the lookup patterns used in the app
CREATE INDEX IF NOT EXISTS idx_user_klaster_id ON "User" (klaster_id);
CREATE INDEX IF NOT EXISTS idx_kategorial_user_id ON kategorial (user_id);
CREATE INDEX IF NOT EXISTS idx_kategorial_klaster_id ON kategorial (klaster_id);
CREATE INDEX IF NOT EXISTS idx_kategorial_nama ON kategorial (nama);
CREATE INDEX IF NOT EXISTS idx_produk_kategori_id ON produk (kategori_id);
CREATE INDEX IF NOT EXISTS idx_produk_created_by ON produk (created_by);
CREATE INDEX IF NOT EXISTS idx_produk_klaster_id ON produk (klaster_id);
CREATE INDEX IF NOT EXISTS idx_akun_kas_user_id ON akun_kas (user_id);
CREATE INDEX IF NOT EXISTS idx_akun_kas_klaster_id ON akun_kas (klaster_id);
CREATE INDEX IF NOT EXISTS idx_lapkeuangan_id_user ON lapkeuangan (id_user);
CREATE INDEX IF NOT EXISTS idx_lapkeuangan_akun_id ON lapkeuangan (akun_id);
CREATE INDEX IF NOT EXISTS idx_lapkeuangan_klaster_id ON lapkeuangan (klaster_id);
CREATE INDEX IF NOT EXISTS idx_lapkeuangan_created_at ON lapkeuangan (created_at);
CREATE INDEX IF NOT EXISTS idx_detail_laporan_id ON detaillaporanbarang (laporan_id);
CREATE INDEX IF NOT EXISTS idx_detail_produk_id ON detaillaporanbarang (produk_id);
CREATE INDEX IF NOT EXISTS idx_invite_klaster_id ON klaster_invite (klaster_id);
CREATE INDEX IF NOT EXISTS idx_invite_target_user_id ON klaster_invite (target_user_id);
CREATE INDEX IF NOT EXISTS idx_invite_created_by ON klaster_invite (created_by);
CREATE INDEX IF NOT EXISTS idx_invite_token ON klaster_invite (token);
CREATE INDEX IF NOT EXISTS idx_rules_user_id ON kategori_auto_rules (user_id);
CREATE INDEX IF NOT EXISTS idx_rules_klaster_id ON kategori_auto_rules (klaster_id);